// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLig3zYN8EP1I_i4FZa0Gx34TfFfIP5aI',
    appId: '1:789367667230:web:4e6a3806587ca587c68c0f',
    messagingSenderId: '789367667230',
    projectId: 'flutterfinal-8cb16',
    authDomain: 'flutterfinal-8cb16.firebaseapp.com',
    databaseURL: 'https://flutterfinal-8cb16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfinal-8cb16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt3g9X1IWi1KuoCQT8TsLkZB7nNSauk9s',
    appId: '1:789367667230:android:6863b232e9ce4fe0c68c0f',
    messagingSenderId: '789367667230',
    projectId: 'flutterfinal-8cb16',
    databaseURL: 'https://flutterfinal-8cb16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfinal-8cb16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnwYnaw8boxbx1AlJ4o3Q4sXi6HI66SM8',
    appId: '1:789367667230:ios:74ea2efe5053b327c68c0f',
    messagingSenderId: '789367667230',
    projectId: 'flutterfinal-8cb16',
    databaseURL: 'https://flutterfinal-8cb16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfinal-8cb16.appspot.com',
    iosBundleId: 'com.sparkew.doctoLibre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnwYnaw8boxbx1AlJ4o3Q4sXi6HI66SM8',
    appId: '1:789367667230:ios:74ea2efe5053b327c68c0f',
    messagingSenderId: '789367667230',
    projectId: 'flutterfinal-8cb16',
    databaseURL: 'https://flutterfinal-8cb16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfinal-8cb16.appspot.com',
    iosBundleId: 'com.sparkew.doctoLibre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLig3zYN8EP1I_i4FZa0Gx34TfFfIP5aI',
    appId: '1:789367667230:web:d20fe5f0f46403b8c68c0f',
    messagingSenderId: '789367667230',
    projectId: 'flutterfinal-8cb16',
    authDomain: 'flutterfinal-8cb16.firebaseapp.com',
    databaseURL: 'https://flutterfinal-8cb16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfinal-8cb16.appspot.com',
  );

}